#!/bin/bash

function usage() {
    echo "Usage:  $0 inc|dec"
    echo
    echo "    Increases or decreases the volume on all pulse audio outputs by 5%"
    echo
    exit 1
}

if [ "X$1" == "X" ]; then
    usage
else

case "$1" in

   inc)
   VOLUME='+5%';;

   dec)
   VOLUME='-5%';;

   *)
   usage;;
esac

for SINK in $(pacmd list-sinks | grep 'index:' | cut -b12-)
do
   pactl set-sink-volume $SINK $VOLUME
done

fi

